### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#1]
There's no Makefile, no INSTALL doc, and nothing in the README that says how to build this.  It's just a pile of Go source files, and I'm not a Go programmer so I don't know what to do.

After some searching, it seems that typing `go build` gives a working executable.  A simple note to that effect in the README would have been super helpful.

**Comment by kstenerud** [comment]
Hey sorry, yeah this tool hasn't received much love since I've been focusing my attention on the spec and the reference implementation. It's probably using a horribly outdated CE snapshot as well, so time to fix that!

**Comment by kstenerud** [comment]
Added in the latest commit.
