### ISSUE TITLE
Can reference alphabetic marks, but not numeric

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#15]
Background: I'm playing around with how to encode a table (think CSV).  In JSON, each record has to repeat all the keys, which can be awfully verbose.  CE has a few possible methods to avoid this problem.

First I tried this, and it seems OK:

```
echo 'c1  (keys = [&a:foo &b:bar]){$a = 1 $b = 2}' | ./enctool convert -df cte
c0
(
    keys = [
        &a:foo
        &b:bar
    ]
){
    $a = 1
    $b = 2
}
```

Then I thought that numbers would be an easier sequence for an application to generate, so I tried that:

```
$ echo 'c1  (keys = [&1:foo &2:bar]){$1 = 1 $2 = 2}' | ./enctool convert -df cte
c0
(
    keys = [
        &1:foo
        &Marked object id [1] of type 4 is not a valid type to be referenced here
```

I don't see anything in the Marker ID spec that would cause alphabetic/numeric IDs to be treated any differently, but they are.

**Comment by kstenerud** [comment]
That's definitely a bug, and it feels like it's related to another int-reference bug I've been chasing down.

**Comment by kstenerud** [comment]
Alright, fixed in the latest:

```
$ echo 'c1  (keys = [&1:foo &2:bar]){$1 = 1 $2 = 2}' | ./enctool convert -df cte
c0
(
    keys = [
        &1:foo
        &2:bar
    ]
){
    $1 = 1
    $2 = 2
}
```
