### ISSUE TITLE
Compact Time in CBE doesn't match documentation

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#16]
The "Compact Time" example [in the spec](https://github.com/kstenerud/compact-time/blob/master/compact-time-specification.md#compact-time) says that 23:59:59 should be:

> Encoded: `[b8 f7 fb]`

The tool doesn't generate quite the same bit pattern, though:
```
$ echo 'c1 23:59:59' | ./enctool convert -df cbe | hexdump -C
00000000  03 00 9a d8 f7 fb                                 |......|
00000006
```

When I tried decoding `[b8 f7 fb]`, I get 23:59:55:

```
$ cat /tmp/almost.cbe | hexdump -C
00000000  03 00 9a b8 f7 fb                                 |......|
00000006
$ cat /tmp/almost.cbe | ./enctool convert -df cte
c0
23:59:55
```

It looks like something's getting flipped around.

**Comment by kstenerud** [comment]
Yup, it's supposed to be `[d8 f7 fb]`. I've put in a fix to the spec.
