### ISSUE TITLE
Relationships not parsed

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#17]
The first example of a Relationship in the spec doesn't parse with enctool:

```
$ cat | ./enctool validate
c1 [
    @[|r https://springfield.gov/people#homer_simpson| |r https://example.org/wife| |r https://springfield.gov/people#marge_simpson|]
    @[|r https://springfield.gov/people#homer_simpson| |r https://example.org/employer| |r https://springfield.gov/employers/nuclear_power_plant|]
]
offset 11 (line 2, col 8): Malformed UUID or unknown named value: [[]
```

It seems like this hasn't been implemented yet, but it doesn't have the usual "TODO" message for unhandled types, so maybe it got missed.

**Comment by kstenerud** [comment]
Relationships are not added yet, but they share the `@` initiator with named values and UUIDs, so it chokes there :)

**Comment by kstenerud** [comment]
Relationships should be working now.

**Comment by kengruven** [comment]
Looks good here!
