### ISSUE TITLE
Plain `na` not parsing

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#19]
According to [the spec](https://github.com/kstenerud/concise-encoding/blob/master/cte-specification.md#na), plain `na` with no reason should be valid.  According to the CBE spec, it's a shorthand for `na:nil`.

This syntax isn't recognized by enctool:

```
$ echo 'c1 na:nil' | enctool convert -df cbe | hexdump
0000000 03 00 94 e0 7e                                 
0000005
$ echo 'c1 na' | enctool convert -df cbe | hexdump
offset 5 (line 1, col 6): unexpected [0x0a] while decoding NA
0000000 03 00                                          
0000002
```

**Comment by kstenerud** [comment]
Whoops, that's leftover from before. NA always requires a reason now and the shorthand no longer exists. I'll update the CTE spec.
