### ISSUE TITLE
Auto-detect format

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#2]
This tool is great for converting/verifying/pretty-printing CE.  It's frustrating, though, that I always have to provide the input format (CTE or CBE).  Why make the user provide that?  The computer can easily determine which it is by looking at the first byte of the input.

**Comment by kstenerud** [comment]
Yup, that's a relic from the past when CBE didn't have the detectable 0x03 byte at the start. I can add in auto-detect now that the format supports it!

**Comment by kstenerud** [comment]
Added in the latest commit.

**Comment by kengruven** [comment]
Nice, thanks.

Nit: the "print" command still doesn't auto-detect.

**Comment by kstenerud** [comment]
Whoops, fixed
