### ISSUE TITLE
CTE time parsing fails on 1-digit hours

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#20]
There are two examples of times in the CTE spec (`4:00:00/Asia/Tokyo`, `9:00:00/L`) that use 1-digit hour fields, and they fail to parse with enctool:

```
$ echo 'c1 4:00:00/Asia/Tokyo' | enctool convert -df cbe | hexdump
offset 4 (line 1, col 5): unexpected [:] while decoding time
0000000 03 00                                          
0000002
```

With a zero-padded 2-year hour ("04:00:00"), they work fine.

The CTE spec says nothing about the minimum number of digits in any temporal field (or any other field at all, except for time zone offsets which are defined as "±hhmm").

The date type has an example in the CTE spec with single digits (`2019-8-5`), and that works fine.  Even bytes in array types don't require zero-padding:

```
$ echo 'c1 |u8x 1 2 3 4 5 6 7 8 9 a|' | enctool convert -df cbe | hexdump
0000000 03 00 95 14 01 02 03 04 05 06 07 08 09 0a      
000000e
```

It's only the time fields which require zero padding.  Interestingly, both of the other subfields have an error message for that, but for hours it shows a generic error:

```
$ echo 'c1 04:00:0' | enctool convert -df cte
c0
offset 9 (line 1, col 10): Second field must be 2 characters long
$ echo 'c1 04:0:00' | enctool convert -df cte
c0
offset 6 (line 1, col 7): Minute field must be 2 characters long
$ echo 'c1 4:00:00' | enctool convert -df cte
c0
offset 4 (line 1, col 5): unexpected [:] while decoding time
```

So I'm not sure if enctool or the spec is mistaken, but they don't agree here.

**Comment by kstenerud** [comment]
Min digits and max digits are in the tables [here](https://github.com/kstenerud/concise-encoding/blob/master/cte-specification.md#date) and [here](https://github.com/kstenerud/concise-encoding/blob/master/cte-specification.md#time)

But actually, requiring 2-digit hour values is a bit too asinine so I've changed it to min 1 max 2 and upgraded enctool to the latest.

**Comment by kengruven** [comment]
Wow, I could have sworn I searched all over and didn't see those columns.  Maybe I was looking at the CE spec by mistake.  (The CE spec has a lot of the same CTE examples and CTE-specific information, too.)  Oh well.  Thanks.
