### ISSUE TITLE
Upper case

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#21]
Currently, enctool accepts upper-case in several places that it seems only lower-case should be allowed:

- hex integers, like `0XFF` (both the radix indicator and the digits)
- special floats, like `nAN` and `iNF` (as long as the first character is lower-case)
- `nIL` (as long as the first character is lower-case)
- `nA` (as long as the first character is lower-case)
- UUIDs, like `A23E4567-E89B-12D3-A456-426655440000`
- array type designators, like `|F32 1|`

**Comment by kstenerud** [comment]
Yes, the spec requires that a decoder accept uppercase, and forbids an encoder from producing uppercase. This is because humans will do it wrong. https://github.com/kstenerud/concise-encoding/blob/master/cte-specification.md#letter-case

However, the keyword issues (`nAN` etc) are a bug.

**Comment by kstenerud** [comment]
keyword issue fix: https://github.com/kstenerud/go-concise-encoding/commit/349ecc71da0e7bb76f3a165904f5937e20c67f8f

**Comment by kengruven** [comment]
OK, that was not at all clear to me.  On further inspection, apparently I only read:

> "Everything else, including hexadecimal digits, exponents, and escape sequences, must be lower case."

and missed the following sentence which seems to contradict that:

> "A decoder must accept data regardless of letter-case because humans will inevitably break these rules, and rejecting a document on such grounds would result in poor UX."

(The word "MUST" is defined as "If this directive is not adhered to, the document or implementation is invalid/non-conformant".  Or does that mean that a conformant implementation must accept non-conformant documents?)

**Comment by kstenerud** [comment]
Good point. I've explicitly added an overriding rule for CTE decoders https://github.com/kstenerud/concise-encoding/commit/363e1a4218c7bb0111dfeb6e178ad86b49dbcc76 and have put links wherever letter case is mentioned.

**Comment by kengruven** [comment]
Confirmed fixed.
