### ISSUE TITLE
-0

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#22]
The spec specifically says `-0` is invalid, as "-0 CANNOT be represented as an integer".

enctool not only accepts it, but emits it:

```
$ echo 'c1 -0' | ./enctool convert -df cte
c0
-0
```

It's only printed this way in CTE.  In CBE, it's byte 0x00, just like normal 0.

**Comment by kstenerud** [comment]
Negative zero is allowed, but it must be a floating point value (CTE is passing it along as an int).

Test case:

```cte
{
    "name" = "-0"
    "issue link" = @"https://github.com/kstenerud/enctool/issues/22"
    "cte" = "\.%%%%
c0
-0
    %%%%"
    "cbe" = |u8x 83 00 65 03|
    "events" = [
                    "bd" "v 0" "df -0" "ed"
                ]
    "from"   = ["t" "b" "e"]
    "to"     = ["t" "b" "e"]
}
```

**Comment by kstenerud** [comment]
Fixed here: https://github.com/kstenerud/go-concise-encoding/commit/122f7d10eef2b8fbf9b093c309ff069c0eb66b18
