### ISSUE TITLE
Comment spacing too lenient

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#23]
[The spec](https://github.com/kstenerud/concise-encoding/blob/master/cte-specification.md#comment) says:

> "Comments have the same placement requirements as regular objects. This means for example that butting up the comment against an object is not allowed (i.e. `"a"/* comment */` and `/ *comment */"a"` are not allowed)."

The second example here has a typo, and with that fixed, this is incorrectly allowed:

```
$ echo 'c1 /* comment */"a"' | ./enctool convert -df cte
c0
/* comment */
"a"
```

**Comment by kstenerud** [comment]
Spec updated: https://github.com/kstenerud/concise-encoding/commit/1d85c1ef956df3e22d0721a907fae7e2e3bd3757

Structural whitespace rules are now enforced: https://github.com/kstenerud/go-concise-encoding/commit/946ce275cceff4fd2399f9922f11b427e6523169

**Comment by kengruven** [comment]
Spacing check looks good.
