### ISSUE TITLE
Hex input gives EOF in comment?

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#25]
Here's a simple document, and I can convert it to CBE:

```
$ echo 'c1 /* A */ 5' | ./enctool convert -df cbe | hexdump -C
00000000  03 00 77 81 41 7b 05                              |..w.A{.|
00000007
```

But if I try to use the [new hex input functionality described here](https://github.com/kstenerud/concise-encoding/issues/19#issuecomment-830805488) to parse these bytes, it gets stuck at the comment:

```
$ echo "0x03 0x01 0x77 0x81 0x41 0x7b 0x05" | ./enctool convert -t -sf cbe -df cte
c0
/*EOF
```

It even happens if I pipe it directly to itself:

```
$ echo 'c1 /* A */ 5' | ./enctool convert -df cbe -C | ./enctool convert -t -sf cbe -df cte
c0
/*EOF
```

Strangely, it's fine with parsing the CBE of this as raw bytes:

```
$ echo 'c1 /* A */ 5' | ./enctool convert -df cbe | ./enctool convert -df cte
c0
/* A */
5
```

**Comment by kstenerud** [comment]
This was an incorrect counting increment issue. Fixed here: https://github.com/kstenerud/enctool/commit/83aaf1c934a63a7692596e6676e989b808e445de
