### ISSUE TITLE
Collapsible whitespace is excessively collapsed

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#26]
The [comment spec](https://github.com/kstenerud/concise-encoding/blob/master/ce-structure.md#comment) says:

> "Whitespace in a comment string is treated the same as in markup content strings."

The [markup spec](https://github.com/kstenerud/concise-encoding/blob/master/ce-structure.md#content-string) says:

> "If the last line ends in collapsible whitespace and is not otherwise empty, the collapsible whitespace at the end MUST be converted to a single space (U+0020)."

This requirement doesn't seem to be implemented:

```
$ echo 'c1 /* hello     */ 5' | ./enctool convert -df cbe|hexdump -C
00000000  03 00 77 85 68 65 6c 6c  6f 7b 05                 |..w.hello{.|
0000000b
```

I tried with `//` comments, `/*` comments, and `<` markup, and it doesn't seem to work for any of them yet.

**Comment by kstenerud** [comment]
I've changed the policy now. All whitespace in comments is preserved.
