### ISSUE TITLE
Validation of empty doc fails

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#4]
The [CTE spec](https://github.com/kstenerud/concise-encoding/blob/master/cte-specification.md#empty-document) says:

> An empty document in CBE is signified by using the NA type with reason NA as the top-level object:
>
>     c1 @na:@na

However, when I try to validate this with "enctool", it fails:

    $ echo 'c1 @na:@na' > empty.cte
    $ ./enctool validate -f empty.cte -fmt cte
    offset 3 (line 1, col 4): Malformed UUID or unknown named value: [na]

I see this error message in ExtractUUID(), which is called from advanceAndDecodeNamedValueOrUUID(), which looks at a glance as if it should handle the `@na` case, but I am not a Go programmer.

**Comment by kengruven** [comment]
I tried changing the "go.mod" to point to the current "go-concise-encoding", and now it gives a different error:

    $ ./enctool validate -f empty.cte -fmt cte
    End Document Rule does not allow NA

**Comment by kstenerud** [comment]
I've updated the CE ref to the latest, but you've also found a bug! `c1 @na` (the shorthand for `@na:@na`) works, but `c1 @na:@na` breaks for some reason...

**Comment by kstenerud** [comment]
Should be fixed in the latest commit.

**Comment by kengruven** [comment]
Looks good here.  Thanks!
