### ISSUE TITLE
Marker ID parsing

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#5]
I was curious if Markers/References could be used to serialize circular data structures, so I pasted the Marker example from the CTE spec into a new text file:

```
c1 [
    &remember_me:"Pretend that this is a huge string"
    &1:{a = 1}
]
```

and ran `./enctool print -f marker.cte`.  It said:

    BUG: *builder.markerIDBuilder (building type interface {}) cannot respond to BuildFromArray

After playing with it for a bit, I noticed that when I change "remember_me" to an int, it succeeds, so my first guess is that strings as Marker IDs simply haven't been implemented yet.

**Comment by kstenerud** [comment]
Yes, I'm working on this bug currently. There's also a bug in the rules engine pertaining to markers inside containers in certain situations currently. The idea of markers/reference is to allow multiple references to a large object, and also to support recursive or cyclical data.

**Comment by kengruven** [comment]
That example now works with numeric marker IDs, and a circular document (`c1 &1:{"a" = $1}`) works fine, too.  Closing.
