### ISSUE TITLE
Pretty-printing / formatting feature

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#9]
One thing I often want to do is pretty-print my CTE in standard format.  Unfortunately, enctool doesn't permit this directly:

```
$ cat foo.cte | ./enctool convert -df cte
cte-cte: Unknown converter
```

My workaround is to convert to CBE and back:

```
$ cat foo.cte | ./enctool convert -df cbe | ./enctool convert -df cte
```

It would be nice if enctool allowed "conversion" of CTE->CTE directly.

**Comment by kstenerud** [comment]
Great idea! Added to the latest commit. All formats can now be "converted" to the same format.

```
$ echo "c1 {a=@na b=2005-1-12/12:45:00.091/America/New_York}" |./enctool convert -df cte
c0
{
    a = @na
    b = 2005-01-12/12:45:00.091/America/New_York
}
```

**Comment by kengruven** [comment]
Looks good!  Thanks.
